### PR TITLE
Protobuf complex type support

### LINKED ISSUE #392: Implement to_proto support for Date32(Day)
I am trying to run the tpch example and hit this error:

```
Error: General("logical_plan::to_proto() Unsupported data type Date32(Day)")
```

### PR DESCRIPTION
**Pull request by pjmore**
Added support for all scalar values to be serialized/deserialized. The serialization and serialization code for Scalar Lists and complex arrow types is recursive so there is the potential to blow the stack out on extremely nested type definitions. Another disadvantage of the current protobuf definitions is things become a bit of an enum soup.

Closes #392

### CODE REVIEW

File: rust/ballista/src/serde/logical_plan/from_proto.rs [hunk 1]
```diff
@@ -253,79 +194,450 @@ impl TryInto<datafusion::logical_plan::DFSchemaRef> for protobuf::Schema {
...
+            arrow_type::ArrowTypeEnum::LargeUtf8(_) => DataType::LargeUtf8,
+            arrow_type::ArrowTypeEnum::Binary(_) => DataType::Binary,
+            arrow_type::ArrowTypeEnum::FixedSizeBinary(size) => DataType::FixedSizeBinary(*size),
+            arrow_type::ArrowTypeEnum::LargeBinary(_) => DataType::LargeBinary,
+            arrow_type::ArrowTypeEnum::Date32(date_unit) => DataType::Date32(protobuf::DateUnit::from_i32_to_arrow(*date_unit)?),
+            arrow_type::ArrowTypeEnum::Date64(date_unit) => DataType::Date64(protobuf::DateUnit::from_i32_to_arrow(*date_unit)?),
+            arrow_type::ArrowTypeEnum::Duration(time_unit) => DataType::Duration(protobuf::TimeUnit::from_i32_to_arrow(*time_unit)?),
+            arrow_type::ArrowTypeEnum::Timestamp(protobuf::Timestamp { time_unit, timezone }) => DataType::Timestamp(
+                protobuf::TimeUnit::from_i32_to_arrow(*time_unit)?,
+                match timezone.len() {
```
Comment (edrevo) [inline rust/ballista/src/serde/logical_plan/from_proto.rs:268]: how come prost isn't generating an Option for this field? i thought everything was optinal in protobuf

File: rust/ballista/src/serde/logical_plan/from_proto.rs [hunk 2]
```diff
@@ -420,40 +724,52 @@ fn from_proto_binary_op(op: &str) -> Result<Operator, BallistaError> {
...
+                let mut field_name_idx = field_names.len() - 1;
+                let mut scalar_type = arrow::datatypes::DataType::List(Box::new(Field::new(&field_names[field_name_idx][..], pb_scalar_type.into(), true)));
+
+                for _ in 0..*depth {
+                    field_name_idx = field_name_idx - 1;
+                    let temp_scalar_type = arrow::datatypes::DataType::List(Box::new(Field::new(&field_names[field_name_idx][..], scalar_type, true)));
+                    scalar_type = temp_scalar_type;
+                }
+                scalar_type
+            }
```
Comment (edrevo) [inline rust/ballista/src/serde/logical_plan/from_proto.rs:767]:
```suggestion
        let pb_scalartype = self
            .datatype
            .as_ref()
            .ok_or_else(|| proto_error("ScalarType message missing required field 'datatype'"))?;
            .into()
```

File: rust/ballista/src/serde/logical_plan/from_proto.rs [hunk 3]
```diff
@@ -508,19 +824,38 @@ fn from_proto_arrow_type(dt: i32) -> Result<DataType, BallistaError> {
...
 
+impl TryInto<arrow::datatypes::Field> for &protobuf::Field {
+    type Error = BallistaError;
+    fn try_into(self) -> Result<arrow::datatypes::Field, Self::Error> {
+        let pb_datatype = self
+            .arrow_type
+            .as_ref()
+            .ok_or_else(|| proto_error("Protobuf deserialization error: Field message missing required field 'arrow_type'"))?;
+
+        Ok(arrow::datatypes::Field::new(&self.name[..], pb_datatype.as_ref().try_into()?, self.nullable))
```
Comment (edrevo) [inline rust/ballista/src/serde/logical_plan/from_proto.rs:855]: opinionated readability nit: it took me a bit to figure out what `&variable[..]` was doing. you can achieve the same thing with `v.as_str()`.

**Review by edrevo — COMMENTED** [review]
Great work! Here's a mix and match of feedback and questions 😄

File: rust/ballista/src/serde/logical_plan/from_proto.rs [hunk 4]
```diff
@@ -253,79 +194,450 @@ impl TryInto<datafusion::logical_plan::DFSchemaRef> for protobuf::Schema {
...
+                let pb_scalar_enum = protobuf::PrimitiveScalarType::from_i32(*scalar_type)
+                    .ok_or_else(|| proto_error("Protobuf deserialization error, scalar_type::Datatype missing was provided invalid enum variant"))?;
+                pb_scalar_enum.into()
+            }
+            Datatype::List(protobuf::ScalarListType {
+                depth,
+                deepest_type,
+                field_names,
+            }) => {
+                if *depth != (field_names.len() - 1) as u64 {
```
[the remark this answers is not in the document]
Comment (pjmore) [reply rust/ballista/src/serde/logical_plan/from_proto.rs:216]: That's a good question and I have no clue. BigQuery allows for empty lists but I don't know if that's standard SQL or not.

File: rust/ballista/src/serde/logical_plan/from_proto.rs [hunk 5]
```diff
@@ -253,79 +194,450 @@ impl TryInto<datafusion::logical_plan::DFSchemaRef> for protobuf::Schema {
...
+    fn try_into(self) -> Result<arrow::datatypes::DataType, Self::Error> {
+        use protobuf::scalar_type::Datatype;
+        Ok(match self {
+            Datatype::Scalar(scalar_type) => {
+                let pb_scalar_enum = protobuf::PrimitiveScalarType::from_i32(*scalar_type)
+                    .ok_or_else(|| proto_error("Protobuf deserialization error, scalar_type::Datatype missing was provided invalid enum variant"))?;
+                pb_scalar_enum.into()
+            }
+            Datatype::List(protobuf::ScalarListType {
+                depth,
```
[the remark this answers is not in the document]
Comment (pjmore) [reply rust/ballista/src/serde/logical_plan/from_proto.rs:212]: It absolutely is, I'll change that definition.

File: rust/ballista/proto/ballista.proto [hunk 6]
```diff
@@ -384,39 +377,181 @@ message Field {
...
+    INT16 = 4;
+    UINT32 = 5;
+    INT32 = 6;
+    UINT64 = 7;
+    INT64 = 8;
+    FLOAT32 = 9;
+    FLOAT64 = 10;
+    UTF8 = 11;
+    LARGE_UTF8 = 12;
+    DATE32 = 13;
```
[the remark this answers is not in the document]
Comment (pjmore) [reply rust/ballista/proto/ballista.proto:484]: This type is supposed to map to  datafusion::scalar::ScalarValue, except for lists, and not the more complex arrow datatypes. So in this this enum's  Date32 isn't really equivalent to Date32(_) but Date32(DateUnit::Day), because ScalarValue::Date32 always uses Day units. This is also why instead of Time32 or Time64 I used TIME_MICROSECOND and TIME_NANOSECOND as ScalarValue only has 64 bit time values.  I'll change this to differentiate and document the implicit units for those enum variants in.

File: rust/ballista/src/serde/logical_plan/from_proto.rs (hunk 1 above)
Comment (pjmore) [reply rust/ballista/src/serde/logical_plan/from_proto.rs:268]: Are you referring to the Timestamp match arm? If so, I believe that is due to the oneof statement, which allows prost to assume that the Timestamp message will always be present.

File: rust/ballista/src/serde/logical_plan/from_proto.rs (hunk 3 above)
Comment (pjmore) [reply rust/ballista/src/serde/logical_plan/from_proto.rs:855]: Definitely more readable that way. I think I did this in a couple places, I'll change those to as_str().

File: rust/ballista/src/serde/logical_plan/from_proto.rs [hunk 7]
```diff
@@ -253,79 +194,450 @@ impl TryInto<datafusion::logical_plan::DFSchemaRef> for protobuf::Schema {
...
+}
+
+impl TryInto<arrow::datatypes::DataType> for &protobuf::scalar_type::Datatype {
+    type Error = BallistaError;
+    fn try_into(self) -> Result<arrow::datatypes::DataType, Self::Error> {
+        use protobuf::scalar_type::Datatype;
+        Ok(match self {
+            Datatype::Scalar(scalar_type) => {
+                let pb_scalar_enum = protobuf::PrimitiveScalarType::from_i32(*scalar_type)
+                    .ok_or_else(|| proto_error("Protobuf deserialization error, scalar_type::Datatype missing was provided invalid enum variant"))?;
```
[the remark this answers is not in the document]
Comment (pjmore) [reply rust/ballista/src/serde/logical_plan/from_proto.rs:208]: Yeah that's a good idea.

**Review by edrevo — APPROVED** [review]

**Review by andygrove — APPROVED** [review]
This is awesome. Thanks so much @pjmore
